### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by mathmul** [Dan503/time-input-polyfill#37]
# Steps to reproduce

1. Open Firefox 92.0.1 (64-bit)
2. Go to [example page](https://dan503.github.io/time-input-polyfill/).
3. Click on "Polyfill time input" or "Polyfill with value" input.

# Result

Behaves exactly the same as real inputs above the corresponding polyfill ones.

# Expected behaviour

Opens time picker (somewhat like [this date picker](https://github.com/jcgertig/date-input-polyfill)).

**Comment by Dan503** [comment]
I don't quite understand, are you asking for a pop up thing to appear?

**Comment by Dan503** [comment]
> Behaves exactly the same as real inputs above the corresponding polyfill ones.

That is the expected behavior. 

This is a polyfill not a plug in.

It is designed to only be loaded in browsers that do not support `<input type="time" />` natively and supply a minimal UI to provide time input functioanlity.

Firefox 92.0.1 has native time input support so that is not a target browser.

The demo page has got the "Polyfill time input" and "Polyfill with value" examples for the sake of demonstrating the difference between the native version and the polyfill version.

The goal is for the native version and the polyfill version to have the least number of differences as possible.

When you say "Behaves exactly the same as real inputs above the corresponding polyfill ones." that means it is working exactly as expected.

**Comment by mathmul** [comment]
It seems like I misunderstood the package's intention.

I opened the example page in Chrome (left) and Firefox (right) side by side now and I now see the package does the exact oposite of what I expected.

![image](https://user-images.githubusercontent.com/25301301/138664826-7c71a90f-e12c-485a-9af1-3834c027b2c4.png)

I was trying to get `<input type="time">` fields to work in Firefox the same as they do in Chrome by default. This means the time would be localized, there would be an icon near the end of the input, and clicking the icon, opens an easy to select UI. I wanted to avoid using a jQuery library (or something) to achieve similar (and useful) UI in both browsers (and Safari, Edge and mobile browsers as well).

Thank you for clarifying.

**Comment by Dan503** [comment]
Yeah, this package is for browsers like IE11 that have no support whatsoever.

I saw other packages with the sort of functionality you are after. I built this because I wanted a lighter weight alternative with a less intrusive UI.

The polyfill doesn't support 24hr time. It is something I eventually intend to support but it isn't high on my priority list.
